version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/1
    command: bundle exec rails server -b 0.0.0.0

  redis:
    image: redis:alpine